### ISSUE TITLE
Please define outside collaborators in code

### ISSUE THREAD

**Issue by NickWalt01** [ministryofjustice/bankline-direct-parser#8]
Hi there

We have a process to manage github collaborators in code: https://github.com/ministryofjustice/github-collaborators

Please follow the procedure described there to grant @ibrechin access to this repository.

If you have any questions, please post in #ask-operations-engineering on Slack.

If the outside collaborator is not needed, close this issue, they have already been removed from this repository.

**Comment by ushkarev** [comment]
@NickWalt01 he's already listed there:
https://github.com/ministryofjustice/github-collaborators/blob/main/terraform/bankline-direct-parser.tf
as it's not expired yet, is there anything you still want me to do?

**Comment by NickWalt01** [comment]
Automation error: adding user back in manually
